name: Daily Job

on:
  schedule:
    - cron: '0 15 * * *'  # JST 00:00
  workflow_dispatch:

jobs:
  run-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: npm install
    - name: Run Script
      env:
        NOTION_SECRET: ${{ secrets.NOTION_SECRET }}
        NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        MISSKEY_TOKEN: ${{ secrets.MISSKEY_TOKEN }}
        MISSKEY_API_URL: ${{ vars.MISSKEY_API_URL }}
      run: |
        npm run ts-run
